### PR TITLE
better readme

### PR DESCRIPTION
**Pull request by mkilpatr**
Added my readme to the github readme.

### CODE REVIEW

**Comment by mkilpatr** [comment]
Better readme and memory fixed

**Comment by mkilpatr** [comment]
Fixed the root file access to a single time when running and store to memory, some minor loop fixes, and met cut introduced.

**Comment by mkilpatr** [comment]
Met cut only effect the events to be stored in the new smeared file, NOT removing them from the total output

**Comment by mkilpatr** [comment]
Condor jobs have almost entirely completed. Runtime about 1 hour.

**Comment by pastika** [comment]
Please reopen if this is not a dead PR

**Pull request closed without merging**
