### PR TITLE
WIP: Cleanup cuts

### PR DESCRIPTION
**Pull request by jsw-fnal**
Adding the additional cleanup cuts:
LowNeutralJetFilter, MuonJetFilter, ECalNoiseJetFilter, HTRatioDPhiTightFilter

### CODE REVIEW

**Comment by zhenbinwu** [comment]
Thanks for the PR. Actually, can we check these variable vs MET/METPhi, instead of MHT/MHTPhi, 
since we are using MET instead of MHT? thank you

**Comment by jsw-fnal** [comment]
Hmmm, I followed the Ra2b definitions as best as I could, which sometimes use MET and sometimes use MHT.  But I see that Ra2b does not cut on MET and instead cuts on MHT.

How about, for now, I make two versions, one using MET and one using MHT?  Then we can go ahead and get moving on v3 without waiting for studies of MET vs MHT.

**Comment by jsw-fnal** [comment]
I don't know immediately how to run NanoSUSY-Tools.  I can try to run it to test this code in the next couple of days, but if somebody can try it out before then, that would be welcome.

**Comment by zhenbinwu** [comment]
Hi Jon, I think we can jsut move to MET version, as we don't plan to use MHT in the analysis. Also we are expecting larger ntuple size with limited storage space. So it would be good to store the variables needed. 

To run the code, you can follow REAMDE
`python Stop0l_postproc.py -i file:[input file] -s [MC sample name (from sampleSet cfg file)] -e [year]`

**Comment by zhenbinwu** [comment]
@jsw-fnal Can you please find some time to work on this? We would like to start

**Pull request closed without merging**
