### PR TITLE
Qcd smearing

### PR DESCRIPTION
**Pull request by mkilpatr**
Smearing methods.

### CODE REVIEW

**Comment by mkilpatr** [comment]
It looks like the QCDSmearing from the susy2015 has not been updated to include the dev_v3 changes to I can't automatically merge the code.

**Comment by zhenbinwu** [comment]
is this PR still valid?

**Comment by mkilpatr** [comment]
Yes. The reason that there are so many files changed is because my branch is based off of dev_v3 and the susy2015 branch is from dev_v1. It needs to be updated.

**Comment by pastika** [comment]
reopen if this is not a dead PR

**Pull request closed without merging**
