### PR TITLE
Fix Gen Particle Selection

### PR DESCRIPTION
**Pull request by caleb-james-smith**
Fix selection of gen particles using logical_and/or reduce; fixes missing gen photons in QCD.

https://docs.scipy.org/doc/numpy/reference/generated/numpy.ufunc.reduce.html

### CODE REVIEW

**Comment by pastika** [comment]
I approve this PR.  The existing code only caught the first 2 requirements no matter how many GenPArt requirements were specified.  The change in the code fixes this issue and was verified in the QCD MC.

**Comment by caleb-james-smith** [comment]
Tested in this way:
```
python Stop0l_postproc.py -i file:root://cmseos.fnal.gov//eos/uscms/store/user/lpcsusyhad/Stop_production/Summer16_94X_v3/PreProcessed_22Feb2019/QCD_HT100to200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/2016_MINIAODv3_RunIISummer16MiniAODv3-PUMoriond17_94X_v3-v1/190225_211123/0000/prod2016MC_NANO_1.root -e 2016 -m 100
```

**Comment by zhenbinwu** [comment]
looks good. merging

**Comment by caleb-james-smith** [comment]
cheers mate

**Pull request merged**
