### PR TITLE
Dev v5 fast sim btagging

### PR DESCRIPTION
**Pull request by scarletnorberg**
A root file per FastSim year. Also the btag code now reads more like JEC so it is included in the DataDepInputs.

### CODE REVIEW

**Comment by zhenbinwu** [comment]
it seems this branch branch from PR 87. Can you make remove the dependency? Your code has no dependency on those fastsim scripts.

**Comment by zhenbinwu** [comment]
If the process is not found in the precalcuated root file, what is the fall back? 
The current fall back will crash now. 
https://github.com/susy2015/NanoSUSY-tools/blob/master/python/modules/BtagSFWeightProducer.py#L32-L42

**Comment by scarletnorberg** [comment]
I will try to separate them I might have to just do a new PR? I added in the TTBar2016 so all fall backs are the same.

**Comment by zhenbinwu** [comment]
Move to a temp branch as Scarlet mixing the branch with PR 87. Merging this PR so that I can start to work on the dev_v5_fast branch

**Comment by zhenbinwu** [comment]
@scarletnorberg The root files you uploaded didn't split by mass points....

**Pull request merged**
